### ISSUE TITLE
Drupal, ontologies won't load

### ISSUE THREAD

**Issue by german-bortoli** [structureddynamics/Open-Semantic-Framework-Installer#17]
<img width="1429" alt="ontology" src="https://cloud.githubusercontent.com/assets/36618/21937182/f9eb6ce8-d994-11e6-8fda-3a22f3b197da.png">

There is an error on osf module, it seems that sceid is empty on JS

```
<script type="text/javascript">
<!--//--><![CDATA[//><!--
var sceid = ;
//--><!]]>
</script>
```

Should I report this here ?

**Comment by fgiasson** [comment]
@Germanaz0 check the network tab in Firebug. I think this is because some remote WS queries fails.

**Comment by fgiasson** [comment]
@Germanaz0 about your question:

> Should I report this here ?

Normally it should be done on the [OSF for Drupal issue tracker here](https://www.drupal.org/project/issues/osf?categories=1)

**Comment by german-bortoli** [comment]
Thanks, going to report there
