### ISSUE TITLE
Unit test errors after installation

### ISSUE THREAD

**Issue by dschmidtadv** [structureddynamics/Open-Semantic-Framework-Installer#18]
I'm getting the following errors during unit testing after installation. Are those fatal? Do they need to be resolved prior to continuing setup?
Thanks
D.
[installerrors.txt](https://github.com/structureddynamics/Open-Semantic-Framework-Installer/files/815120/installerrors.txt)

**Comment by fgiasson** [comment]
@dschmidtadv no these revision relation errors are not. These happen from time to time and are *dependant* on a specific configuration, so they are hard to reproduce for me. This is a bug in the test suites that I never have been able to reproduce on my end to fix.

You can ignore those without any issues.
