### ISSUE TITLE
error of installation in ubuntu 18.04.1 and php7.4

### ISSUE THREAD

**Issue by danieljyj** [structureddynamics/Open-Semantic-Framework-Installer#21]
I'm currently using ubuntu 18.04 and php 7.4
![default](https://user-images.githubusercontent.com/39069001/43836405-8b3ffd92-9b15-11e8-93ae-6d6597a2fb18.PNG)

And at last I end with this problem.
![2](https://user-images.githubusercontent.com/39069001/43836458-b83a6dc8-9b15-11e8-81bb-14bc34197d8f.PNG)
Option not supported for this linux distribution and version.
Is this unsovlable for now?

Thank you very much

**Comment by fgiasson** [comment]
Hi,

Latest version of Ubuntu is unfortunately not supported at the moment. If someone can add that version to the installer, just create a PR and I will review and merge it.
