### ISSUE TITLE
PHP Fatal error:  Class OSFInstallerGeneric contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (OSFInstaller::installOSFDrupal) in /usr/share/osf-installer/inc/OSFInstallerGeneric.php on line 76

### ISSUE THREAD

**Issue by alexukua** [structureddynamics/Open-Semantic-Framework-Installer#5]
if run ./osf-installer --install-osf -v for fix this error, please update OSFInstallerGeneric.php
--- Индекс
+++ Изменено в рабочем дереве
@@ -73,7 +73,9 @@
     {
       $this->cecho("Option not supported for this Linux distribution and version.\n", 'RED');
     }    
-    public function installOSFDrupal(){
-        return FALSE;  
-    }
- }
  ?>

**Comment by fgiasson** [comment]
Hi alex

Great, I will review and merge when I am back in my office next Monday. This is related to the latest version we released for Ubuntu 14.04. I refactored that class for installing OSF for Drupal and I did forget that so thanks for committing.

**Comment by fgiasson** [comment]
Also if you want you can go ahead and commit that fix in your local repository and do a pull request that I would then merge into the master branch. That way you will get the credit for the fix.

Thanks again

Fred

**Comment by fgiasson** [comment]
Fixed thanks!
